/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Awards } from "./Awards";
export type { Competition } from "./Competition";
export type { GovernorCountingUniversal } from "./GovernorCountingUniversal";
export type { RootstockGovernor } from "./RootstockGovernor";
export type { VoteToken } from "./VoteToken";
