/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { RootstockGovernor__factory } from "./RootstockGovernor__factory";
export { VoteToken__factory } from "./VoteToken__factory";
